### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by mauricelam** [JeffersGlass/emscripten-shell#1]
Hi there,

Very cool project! I played around with both the existing functionality and changing up the code a bit, was excited by the prospects of this. This feels like it can be very useful as a demo tool for some of my other Python projects, but I don't see a LICENSE file in this project. Would you mind adding one, so I can publish my modifications in the fork and use this project for demo? If there are any functionality in the fork that you are interested in, I'll be happy to create PRs for them as well.

**Comment by JeffersGlass** [comment]
Happy to add a license file! The project is now licensed under Apache V2.0 as of [commit aebb9ab](https://github.com/JeffersGlass/emscripten-shell/commit/aebb9ab81b1436e20746d534010b49bcde84082e). 

I'd definitely be interested to see what you're looking at adding/modifying in a fork, if you'd be game to share them.

**Comment by mauricelam** [comment]
Thank you! I've just published my changes in the fork: https://github.com/JeffersGlass/emscripten-shell/compare/main...mauricelam:emscripten-shell:main. I didn't do a good job separating the generally applicable changes form the things specific for my demo, so please bear with that.

The README roughly describes what I changed, copied here for reference:
* Use `local-echo` to support arrow keys and autocomplete
* Added a few commands, like `mkdir` and `grep`
* Support for basic shell syntax, like `&&`, `||`, and `|`. Note that this is very barebones – the execution is not
  concurrent, and exit codes are always assumed to be 0.

I'll be happy to clean up the changes / revert the demo-specific changes and create PRs if desired.
